version: '2.3'
services:
  weewx:
    build: # "context" and "dockerfile" fields have to be under "build"
      context: .
      dockerfile: ./Dockerfile
    container_name: weewx
    volumes:
      - /nas/docker/weewx/sdb/weewx.sdb:/home/weewx/weewx.sdb
      - /nas/web/weewx:/home/weewx/public_html
      - /nas/docker/weewx/conf/weewx.conf:/home/weewx/weewx.conf
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin