version: '2.3'
services:
  weewx:
    image: mitct02/weewx
    container_name: weewx
    volumes:
      - /mnt/docker/weewx/weewx.sbd:/home/weewx/weewx.sbd
      - /mnt/docker/weewx/public_html:/home/weewx/public_html
      - /mnt/docker/weewx/weewx.conf:/home/weewx/weewx.conf
    networks:
      - internal
    restart: unless-stopped
